debug: false
logging:
  level:
    root: info
    systems:
      rajshah:
        "*": debug

# this will update the /actuator/health to /health
management:
  endpoints:
    web:
      base-path: "/"
      
springdoc:  api-docs:    path: "/dev/openAPI"
  swagger-ui:
    operations-sorter: method
    path: "/openAPI.html"  
server:
  port: "${PORT:8080}"

google:
    credentials: 
      location: ./google/google-credentials.json
    
spring:
  cloud:    gcp:
      project-id: "infy-rest-data"      credentials:        location: file:${google.credentials.location}
  application:
    name: "fd-db-info"

#eureka.instance.hostname=${DOAIN_NAME:localhost}
#eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761}/eureka/
   
