# This is a basic workflow that is manually triggered

name: Docker Manual Push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Tag Name for : rajshah1/fdproject-fireap'
        # Default value if no value is explicitly provided
        default: 'v'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Docker-push:
    # The type of runner that the job will run on
    name: Docker Push Run
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      #working-directory: ./firebase-fdproject
    - name: Java Setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        architecturewith: x64
    - name: Build  Maven
      run: |
        echo $GOOGLE_APP_CREDENTIALS > ./google-credentials.json
        #mvn -B package --file pom.xml
      env:
        GOOGLE_APP_CREDENTIALS: ${{ secrets.GOOGLE_APP_CREDENTIALS }}
      shell: bash
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           repository: rajshah1/fdproject-fireapp
           tags:  "${{ github.event.inputs.tag }}"
   #      run: echo "Hello ${{ github.event.inputs.name }}"
